fix rollup data missing points in rob
bloomberg/metrictank pull request #109
Opened 2021-10-19 14:29 UTC by zlin179

Fix for issue https://github.com/grafana/metrictank/issues/1485

**Describe your changes**
The rollup aggregators only get the points once they leave the ROB.
This PR fixs aggregator so when being queried it will return the current value (considering points in ROB) but will not actually consume the points in ROB.

**Testing performed**
* Add some unit tests for it and pass it.
* Integrate test by comparing raw data and rollup data queried at the same time

![debug](https://user-images.githubusercontent.com/92168069/137931738-01c7aa86-3b46-4cf8-aeaa-beb85e84dbec.png)

2021-10-20 08:35 UTC, shanson7 commented
The images in the description are a little confusing. 

1. It seems like they should be reversed to match before/after (e.g. before the fix and then after the fix).
2. I think the mention of 31d should really just be `5-minute rollups` so it has more context outside of BB
3. The first image (the "after") has the wrong text "no 16:55" should probably be "includes 16:30" or "includes most recent time interval".

2021-10-20 08:37 UTC, shanson7 commented
Also in the future it would be good to do multiple commits like:

1. First commit - add test case (that fails)
2. Second commit - add the fix (test case should now pass)

Any other commits (like code cleanup or similar) should also be separate from those 2 commits.

2021-10-20 08:59 UTC, shanson7 requested changes

2021-10-20 08:59 UTC, shanson7 commented on mdata/aggmetric.go
> +	for _, aggregator := range a.aggregators {
This rename change is good (removes shadowing of `a`) but should have been in a separate commit.

2021-10-20 08:59 UTC, shanson7 commented on mdata/aggmetric.go
> +				return Result{}, fmt.Errorf("consolidator %q not configured", consolidator)
Why change this line?

2021-10-20 08:59 UTC, shanson7 commented on mdata/aggmetric.go
> +			}
Couldn't all of this be in the `if` statement above? That reduces the changes required for the non-rob case.

2021-10-20 08:59 UTC, shanson7 commented on mdata/aggmetric_test.go
> -	m.Add(40, 40)
Why remove this?

2021-10-20 08:59 UTC, shanson7 commented on mdata/aggregator.go
> +	if currentBoundary <= to {
Should there be a check for `aggregationPreview.Cnt != 0` here?

2021-10-20 08:59 UTC, shanson7 commented on mdata/aggregator_test.go
> +	// Foresea should not change the acutal state of aggregator
```suggestion
	// Foresee should not change the actual state of aggregator
```

2021-10-20 13:56 UTC, zlin179 commented on mdata/aggmetric_test.go
> -	m.Add(40, 40)
Well there's no ROB in this case. 40 is the boundary of that span. It will return [40, 40] anyway even without `Foresee`. Here I am trying to test if it can return the boundary if the last point is somewhere in the middle and `to >= boundary`

2021-10-20 13:56 UTC, zlin179 commented on mdata/aggmetric.go
> +				return Result{}, fmt.Errorf("consolidator %q not configured", consolidator)
My linter kept complaining that the first letter in `Errorf` should be lower-case. As it is the case for other `Errorf` in this file, I changed it.

2021-10-20 14:02 UTC, shanson7 commented on mdata/aggmetric.go
> +				return Result{}, fmt.Errorf("consolidator %q not configured", consolidator)
Reasonable, but again (in the future) do these things in a separate commit.

2021-10-20 14:02 UTC, shanson7 commented on mdata/aggmetric_test.go
> -	m.Add(40, 40)
But maybe that was on purpose for testing behavior on the boundary condition? Perhaps your intended test should be an additional case?

2021-10-20 14:26 UTC, zlin179 commented on mdata/aggmetric_test.go
> -	m.Add(40, 40)
Well I think the boundary thing (specifically just a `if` branch) is part of the `aggmetric.GetAggregated`. We add some points to test some branches, add some other points to other branches. They are sequentially tested by `expected := []schema.Point`. Here to be convenient I just delete one point because I think 9 points for the previous test (the original logic) is enough. I can also add a new point for the new logic, but I think it's unnecessary to separate them into two functions as they test the same function?

2021-10-20 14:27 UTC, zlin179 commented
> Also in the future it would be good to do multiple commits like:
> 
> 1. First commit - add test case (that fails)
> 2. Second commit - add the fix (test case should now pass)
> 
> Any other commits (like code cleanup or similar) should also be separate from those 2 commits.

Got it. It's just that some repos require clean history and some repos don't care about it lol. I just read the CONTRIBUTING.md here
I kind of twisted the commit history here.

2021-10-20 14:44 UTC, zlin179 commented on mdata/aggmetric.go
> +	for _, aggregator := range a.aggregators {
well, I renamed this because I need the access the outer `a` `a *AggMetric` somewhere in the forloop (specifically the `a.rob` below) while the original code doesn't not need to . If I separate it the code won't work in the first commit

2021-10-20 14:58 UTC, zlin179 commented
> The images in the description are a little confusing.
> 
> 1. It seems like they should be reversed to match before/after (e.g. before the fix and then after the fix).
> 2. I think the mention of 31d should really just be `5-minute rollups` so it has more context outside of BB
> 3. The first image (the "after") has the wrong text "no 16:55" should probably be "includes 16:30" or "includes most recent time interval".

Updated Image
![mt-fix](https://user-images.githubusercontent.com/92168069/138118258-9e53e908-7b42-4ba7-85bd-fb8400a1e530.png)

2021-10-20 15:33 UTC, shanson7 commented
> > Also in the future it would be good to do multiple commits like:
> > 
> > 1. First commit - add test case (that fails)
> > 2. Second commit - add the fix (test case should now pass)
> > 
> > Any other commits (like code cleanup or similar) should also be separate from those 2 commits.
> 
> Got it. It's just that some repos require clean history and some repos don't care about it lol. I just read the CONTRIBUTING.md here I kind of twisted the commit history here.

I think the history is mildly important, but it's also nice when reviewing to decouple the incidental commits and the core commits. I can review the incidental stuff first and then just look at the core commits separately.

2021-10-21 11:32 UTC, shanson7 approved these changes
LGTM. I changed the base branch so this can be merged. Then we can create a PR from this repo to grafana/metrictank

2021-10-21 11:32 UTC, shanson7 commented on mdata/aggmetric.go
> +	for _, aggregator := range a.aggregators {
The first commit could be just the variable rename. No worries though

2021-10-21 11:32 UTC, merged