Add log func
bloomberg/metrictank pull request #110
Opened 2021-10-21 21:48 UTC by zlin179

**Describe your changes**
Add the `log` function similar to Graphite's [log](https://graphite.readthedocs.io/en/latest/functions.html#graphite.render.functions.logarithm)

**Testing performed**
* Unit Test (pass)
* Integration Test (ongoing)

**Additional context**
Benchmark
```
goos: darwin
goarch: amd64
pkg: github.com/grafana/metrictank/expr
cpu: Intel(R) Core(TM) i7-9750H CPU @ 2.60GHz
BenchmarkLog10k_1NoNulls
BenchmarkLog10k_1NoNulls-12                        39400             28115 ns/op
BenchmarkLog10k_10NoNulls
BenchmarkLog10k_10NoNulls-12                        4143            300366 ns/op
BenchmarkLog10k_100NoNulls
BenchmarkLog10k_100NoNulls-12                        342           3290549 ns/op
BenchmarkLog10k_1000NoNulls
BenchmarkLog10k_1000NoNulls-12                        37          30940075 ns/op
BenchmarkLog10k_1SomeSeriesHalfNulls
BenchmarkLog10k_1SomeSeriesHalfNulls-12            43148             27560 ns/op
BenchmarkLog10k_10SomeSeriesHalfNulls
BenchmarkLog10k_10SomeSeriesHalfNulls-12            4471            293390 ns/op
BenchmarkLog10k_100SomeSeriesHalfNulls
BenchmarkLog10k_100SomeSeriesHalfNulls-12            384           3079671 ns/op
BenchmarkLog10k_1000SomeSeriesHalfNulls
BenchmarkLog10k_1000SomeSeriesHalfNulls-12            40          29678756 ns/op
BenchmarkLog10k_1AllSeriesHalfNulls
BenchmarkLog10k_1AllSeriesHalfNulls-12             42213             28313 ns/op
BenchmarkLog10k_10AllSeriesHalfNulls
BenchmarkLog10k_10AllSeriesHalfNulls-12             4590            256792 ns/op
BenchmarkLog10k_100AllSeriesHalfNulls
BenchmarkLog10k_100AllSeriesHalfNulls-12             392           3157942 ns/op
BenchmarkLog10k_1000AllSeriesHalfNulls
BenchmarkLog10k_1000AllSeriesHalfNulls-12             37          30260522 ns/op
PASS
ok      github.com/grafana/metrictank/expr      18.915s
```

2021-10-22 08:05 UTC, shanson7 requested changes

2021-10-22 08:05 UTC, shanson7 commented on expr/func_log.go
> +			// math.Log returns NaN for negative value and -Inf() for 0 value.
To match the [python impl](https://github.com/graphite-project/graphite-web/blob/master/webapp/graphite/render/functions.py#L2916) 0 should result in NaN. Might be worth comparing the other special vals (e.g. +/-Inf) against pythons `math.log`

2021-10-25 21:37 UTC, zlin179 commented
I tested using mtcmptest with the following json
```json
{
    "log()": "log(seriesByTag('name=jitter.g'))",
    "log(0.8)": "log(seriesByTag('name=jitter.g'),0.8)",
    "log(2.73)": "log(seriesByTag('name=jitter.g'),2.73)",
    "log(10)": "log(seriesByTag('name=jitter.g'),10)",
    "log(233333333)": "log(seriesByTag('name=jitter.g'),233333333)"
}

```

Basically they are the same except that the tag for log is `{string: string}` in mt & `{string: float}` in graphite, and very occasionally there's 1 bit precision difference.
[link to](http://paste.dev.bloomberg.com/c4RV8T5yWZk3bGeHzL8L.cs) the comparison result

2021-10-26 07:52 UTC, shanson7 commented on expr/validator.go
> +var ErrPositiveNotOne = errors.NewBadRequest("value must be positive and does not equal to one")
```suggestion
var ErrPositiveNotOne = errors.NewBadRequest("value must be positive and not equal to one")
```

2021-10-26 13:21 UTC, shanson7 approved these changes
LGTM

2021-10-26 15:06 UTC, closed without merging