Unique
bloomberg/metrictank pull request #80
Opened 2020-03-24 13:23 UTC by fqiu7

**Describe your changes**
Add unique function

**Testing performed**
Integration test

2020-03-24 16:35 UTC, shanson7 requested changes
Make sure to update docs/graphite.md

2020-03-24 16:35 UTC, shanson7 commented on expr/func_unique.go
> +	fmt.Println("New UNIQUE func called !!!")
Should be removed

2020-03-24 18:55 UTC, fqiu7 commented on expr/func_unique.go
> +	fmt.Println("New UNIQUE func called !!!")
removed

2020-03-24 18:55 UTC, fqiu7 commented on expr/func_unique.go
> +	fmt.Println("New UNIQUE func called !!!")
I also updated docs/graphite.md

2020-03-25 09:03 UTC, shanson7 approved these changes
Nice work! Leave this PR open and approved as a reminder for me to merge it in to our next release branch. Submit a new PR against grafana/metrictank

2020-03-25 12:51 UTC, fqiu7 commented
sure I will leave this open and submit a new PR against grafana/metrictank.

2020-04-14 14:52 UTC, closed without merging