implement aliasByMetric
bloomberg/metrictank pull request #84
Opened 2020-03-31 19:42 UTC by vaguiar

**Describe your changes**
Native implementation of aliasByMetric

**Testing performed**
Unit tests and integration testing

2020-03-31 19:44 UTC, vaguiar commented on expr/func_aliasbymetric.go
> +		series[i].QueryPatt = n
Note that unlike https://github.com/grafana/metrictank/blob/master/expr/func_aliasbynode.go#L32-L36, I'm not resetting the tags on the output series

2020-03-31 19:45 UTC, vaguiar commented on expr/func_aliasbymetric_test.go
> +	var longMetric string = "report.runtime.d.max;cluster=tkap*;datacenter=!or@ngeb%u<>rg1;gutsReportName=guts-timeseries;gutsReporterJobType=localJob;host=tel-kap-pob-r03-n02.bloomberg.com;namespace=gu
I will mask the tag values here or use generic ones

2020-03-31 21:49 UTC, agao48 commented
don't forget to update https://github.com/grafana/metrictank/blob/master/docs/graphite.md

2020-03-31 21:52 UTC, agao48 approved these changes

2020-04-01 08:38 UTC, shanson7 requested changes
Also update docs/graphite.md

2020-04-01 15:49 UTC, shanson7 approved these changes

2020-04-02 13:57 UTC, merged